theme: jekyll-theme-slate

title: "IMU Sensor Fusion Estimator"
description: "Attitude estimation using gyroscope and accelerometer inputs"

show_downloads: true

github:
  is_project_page: false
  pdf_url: "https://github.com/leetnz/imuAttitudePaper/releases/download/v0.0.0-draft/README.pdf"

